### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by BassmanOff** [brendonjkding/FPSIndicator#1]
iPhone 5, iOS 8.4.1 [вылеты при нажатии "Choose Enabled Games"](https://youtu.be/lq3O0WAzEgY). Несовместимость с другими твиками или FPSIndicator несовместим с iOS 8 ?
Спасибо!
_________
iPhone 5, ios 8.4.1 [crashes when you click "Choose Enabled Games"](https://youtu.be/lq3O0WAzEgY). Incompatibility with other tweaks or is FPSIndicator incompatible with iOS 8 ?
Thanks!

**Comment by brendonjkding** [comment]
Pushed an update to my repo. Does it fix the crash?

**Comment by BassmanOff** [comment]
Yes, everything works now, thank you very much !
