### ISSUE TITLE
Does not work in Rec Room

### ISSUE THREAD

**Issue by Bobrobot1** [brendonjkding/FPSIndicator#2]
It does not work in Rec Room, iOS 14.4, iPhone 7.

**Comment by brendonjkding** [comment]
Fixed in 0.0.3r6 just now.

**Comment by brendonjkding** [comment]
0.0.3r6 was recalled just now because I'm not sure whether it has bad impact on non-UI process. I'd recommend to manually add specific bundle id into `/Library/MobileSubstrate/DynamicLibraries/FPSIndicator.plist`. In this case, for example, `com.AgainstGravity.RecRoomBeta`.
