### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by ghost** [brendonjkding/FPSIndicator#6]
Hello, thanks for this great tweak.  ARM64e A12 iOS 14 this works just in the wrong place and in some games it shows 0 or not at all.

I want to know if you can update this

**Comment by brendonjkding** [comment]
Please provide informations as follow

Device model, iOS version
Jailbreak App name and version
Tweak version and repo.
A Screenshot of those not working Apps in App Store.

Example:
iPhone SE 2,iOS 14.3 / iPad mini5, iOS 14.3
unc0ver 6.1.1 / checkra1n 0.12.2
0.0.1, Bigboss/0.0.1, Brend0n
[screenshot]

**Comment by TurannUl** [comment]
iPhone XR 14.2 Taurine 1.0 
0.0.3r from BigBoss 
Game Among Us!  I hope u know Secreenshot really necessary?

**Comment by brendonjkding** [comment]
It works on this game. Though I'm using unc0ver, it should work out of the box in different jailbreak environment. I don't think there is anything I can do for this objc-level App tweak. 
As for the position issue, the updated version on my repo may have correct place.

**Comment by TurannUl** [comment]
I changed libhooker configration works now

**Comment by TurannUl** [comment]
was off screen due to its location
![B48C2DB0-437D-41AB-8431-5372F33A2C54](https://user-images.githubusercontent.com/70968210/113474091-4fc08180-9476-11eb-8fdb-5b4e0ae65cd7.png)

**Comment by TurannUl** [comment]
> It works on this game. Though I'm using unc0ver, it should work out of the box in different jailbreak environment. I don't think there is anything I can do for this objc-level App tweak.
> As for the position issue, the updated version on my repo may have correct place.

What your repo can share?
